ol:
  ims:
    project:
      mainframeImsSdk:
        host: 192.86.32.238
        port: 9999
        username: DEMO001
        password: '{cipher}f149de1f7cabda956a8c71a0323eeef32c84b0cfd3af501f7fe073c8345bfad2'
        code-page: CP037
        data-store-name: IVP1
        connection-timeout: 5000
        output-offset: 0
        group-name: GROUP1
        ssl-properties:
          ssl-enabled: false
        transaction-properties:
          commit-mode: send-and-commit
          user-message-exit-identifier: HWSSMPL1
          transaction-timeout: 5000
  license:
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wiLCJpc3N1ZWRfYXQiOiIyMDIwLTAxLTIwVDE3OjAwOjAwLjAxWiIsInZhbGlkX2ZvciI6LTF9.K46QmdrFjI3n0yhytMtQB2598jYrJsnWEuFGl8BTJGuc2O20u_XfpJBG9RR2vgWRCpxsNttCg-HGKkgFe5erjvQPz6wC90avvrtJjydLxX82v1zgTbNgAtzuV9zoeu3oI-TMppjE8s0WHT1pLyjva8GXXDbAdCWiO8BfF0Vr-GrFJ2YQw4jW61KzeIPv30GtmYNCrcGxHHstIcf_D6WGCmDivkRWejMLwdVyeAN9oi0IOrrP8obi6FCrSPhh5MhQEHyKvUA1tXxlC1UkMH4avSPdzSqn2DIbo8WUdRJb_OnII9Xg8IPlCrZuuOvwkBFfHMF1JXxhOAaM8bvwKhR3KA