package com.mainframe_ims_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.mainframe_ims_sdk.openlegacy.Imsfin2;
import com.mainframe_ims_sdk.openlegacy.Imsfin2CreditCards;
import com.mainframe_ims_sdk.openlegacy.Imsfin2Imsfin2Input;
import com.mainframe_ims_sdk.openlegacy.Imsfin2Imsfin2Output;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test CreditCardServiceTest.
 *  The interface CreditCardService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "CreditCard")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class CreditCardServiceImpl implements CreditCardService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getCreditCard", entities = {
            @EntityMapping(alias="imsfin2", entity=com.mainframe_ims_sdk.openlegacy.Imsfin2.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "imsfin2.imsfin2Input.custId", expression = "custId")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "imsfin2Output", expression = "imsfin2.imsfin2Output")})
    public CreditCardOut getCreditCard(CreditCardIn creditCardIn) throws Exception {
        CreditCardOut creditCardOut = new CreditCardOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession mainframeImsSdkSession = applicationContext.getBean("mainframeImsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Imsfin2 imsfin2 = serviceBinder.bindInputs(this, "getCreditCard", "imsfin2", new Imsfin2(), creditCardIn);
            imsfin2 = mainframeImsSdkSession.doAction(ActionUtil.getRpcAction(Imsfin2.class), imsfin2);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            creditCardOut = serviceBinder.bindOutput(this, "getCreditCard", creditCardOut, new String[]{"creditCardIn", "imsfin2"}, creditCardIn, imsfin2);
            /* autogenerated - output block end */;

            return creditCardOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            mainframeImsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
