# Logging #
#logging:
#  level:
#    org:
#      openlegacy: debug


management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - olprojectinfo
          - metrics

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

# Springdoc #
springdoc:
  pathsToMatch: /api/**
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger/swagger.json
# OpenLegacy #
ol:
  # OpenLegacy Common Properties (OLCommonProperties) #
  common:
    cache:
      enabled: false
  license:
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wiLCJpc3N1ZWRfYXQiOiIyMDIwLTA5LTA5VDExOjAzOjEwLjMzNVoiLCJ2YWxpZF9mb3IiOi0xfQ.pLPwaVG73DCY1TSOrrvGo_dRIfz2TLXfrbb5qUO-jM1ndchxE1hvwNbNXh1ZZc415OjGAJ1w-QIT9NlXCqTJhnm6eFmnzGYdXbMDGkzW1b6pKQXz_P5pJmw1ZV5TCw-KziYO1Jl9JEGfkK22ITq1Y7Nou5uIdminO1-jAgPMq8V1wToo3MMMPXaN9NmMqQF0y7f9Roc2YJy3jYvy89al3G2VIJAhAOiUPIw0kYoKYK_E31L8GRzqOS85ZJtD12W5qQwmRZxVtlMFDasF7b7GeynljpwlR7xJsxWH8nIClAQFKoZZ9Y9-ZgVZRythQmX3NzN-wbindm47utTRwtGovA
  security:
    db:
      init-schema: true
      clients:
        - client-id: client_id
          client-secret: '{noop}client_secret'
          scope: read,write,trust,ol_admin
          authorized-grant-types: client_credentials

---

# mainframeImsSdk
ol:
  ims:
    project:
      mainframeImsSdk:
        host: 192.86.32.238
        port: 9999
        username: DEMO001
        password: '{cipher}f149de1f7cabda956a8c71a0323eeef32c84b0cfd3af501f7fe073c8345bfad2'
        code-page: CP037
        data-store-name: IVP1
        connection-timeout: 5000
        output-offset: 0
        group-name: GROUP1
        ssl-properties:
          ssl-enabled: false
        transaction-properties:
          commit-mode: send-and-commit
          user-message-exit-identifier: HWSSMPL1
          transaction-timeout: 5000
  license:
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wiLCJpc3N1ZWRfYXQiOiIyMDIwLTAxLTIwVDE3OjAwOjAwLjAxWiIsInZhbGlkX2ZvciI6LTF9.K46QmdrFjI3n0yhytMtQB2598jYrJsnWEuFGl8BTJGuc2O20u_XfpJBG9RR2vgWRCpxsNttCg-HGKkgFe5erjvQPz6wC90avvrtJjydLxX82v1zgTbNgAtzuV9zoeu3oI-TMppjE8s0WHT1pLyjva8GXXDbAdCWiO8BfF0Vr-GrFJ2YQw4jW61KzeIPv30GtmYNCrcGxHHstIcf_D6WGCmDivkRWejMLwdVyeAN9oi0IOrrP8obi6FCrSPhh5MhQEHyKvUA1tXxlC1UkMH4avSPdzSqn2DIbo8WUdRJb_OnII9Xg8IPlCrZuuOvwkBFfHMF1JXxhOAaM8bvwKhR3KA


