package com.as400_pcml_rpc_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.as400_pcml_rpc_sdk.openlegacy.Getcst;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test CustomerServiceTest.
 *  The interface CustomerService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "Customer")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class CustomerServiceImpl implements CustomerService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getCustomer", entities = {
            @EntityMapping(alias="getcst", entity=com.as400_pcml_rpc_sdk.openlegacy.Getcst.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "getcst.customerid", expression = "customerid")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "getcst", expression = "getcst")})
    public CustomerOut getCustomer(CustomerIn customerIn) throws Exception {
        CustomerOut customerOut = new CustomerOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession as400PcmlRpcSdkSession = applicationContext.getBean("as400PcmlRpcSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Getcst getcst = serviceBinder.bindInputs(this, "getCustomer", "getcst", new Getcst(), customerIn);
            getcst = as400PcmlRpcSdkSession.doAction(ActionUtil.getRpcAction(Getcst.class), getcst);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            customerOut = serviceBinder.bindOutput(this, "getCustomer", customerOut, new String[]{"customerIn", "getcst"}, customerIn, getcst);
            /* autogenerated - output block end */;

            return customerOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            as400PcmlRpcSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
