package com.mainframe_ctg_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.mainframe_ctg_sdk.openlegacy.Fininq2;
import com.mainframe_ctg_sdk.openlegacy.Fininq2CreditCards;
import com.mainframe_ctg_sdk.openlegacy.Fininq2Dfhcommarea;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test CardsServiceTest.
 *  The interface CardsService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "Cards")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class CardsServiceImpl implements CardsService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getCards", entities = {
            @EntityMapping(alias="fininq2", entity=com.mainframe_ctg_sdk.openlegacy.Fininq2.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "fininq2.dfhcommarea.custId", expression = "custId")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "creditCards", expression = "fininq2.dfhcommarea.creditCards")})
    public CardsOut getCards(CardsIn cardsIn) throws Exception {
        CardsOut cardsOut = new CardsOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession mainframeCtgSdkSession = applicationContext.getBean("mainframeCtgSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Fininq2 fininq2 = serviceBinder.bindInputs(this, "getCards", "fininq2", new Fininq2(), cardsIn);
            fininq2 = mainframeCtgSdkSession.doAction(ActionUtil.getRpcAction(Fininq2.class), fininq2);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            cardsOut = serviceBinder.bindOutput(this, "getCards", cardsOut, new String[]{"cardsIn", "fininq2"}, cardsIn, fininq2);
            /* autogenerated - output block end */;

            return cardsOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            mainframeCtgSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
